@startuml save key to safe
actor user
participant server as serv
participant tester as test
participant runner as run
participant compiler as com
database dataManager as db

user->serv:save(key text,user token,safe id)
serv->db:get user(user token)
db-->serv:user
alt bad token
    serv-->user:bad token
else
    serv->com:compile key(key text)
    com-->serv:compilation results
    alt faild to compile
        serv-->user:compiolation error
    else
        com-->serv:key bytecode
        serv->tets:test key(key bytecode)
        tets->run:run game(key,demo safe)
        run-->test:results
        alt win
            test-->serv:bad key
            serv-->user:bad key, win unwinnable safe\
        else
            test-->serv:good key
            serv->db:save key(user id,key text,key bytecode,safe id)
            alt save error
                db-->serv:save error
                serv-->user:save error
            else
                db-->serv:key id
                serv-->user:success
            end
        end
    end

    @enduml