@startuml viewData
actor user
participant rowsFactory as row
participant UITable as tab
participant server as serv
database data as db
== show the data==
user->tab:show data
tab->serv:load all tokens
serv->serv:check token
serv->db:load all tokens
serv<--db:all relevant data
tab<--serv:all relevant data
loop for each token in relevant data
    tab->row:generate row(userToken)
    tab<--row:result row
end
tab<-tab:add to table
user<--tab:the result table
==edit the data==
user->tab:edit user(token)
tab->row:generate edible row
row-->tab:edible row
tab->tab:update table
user<--tab:new table
user->tab:update edible row
tab->serv:update data
serv->serv:check token
serv->db:update row
alt can edit
    db->db:update row
    db-->serv:success
    serv-->tab:success
    tab->row:get normal row with edited data
    row-->tab:normal row
    tab->tab:update table
    tab-->user:updated table

else cant edit
    db-->serv:fail
    serv-->tab:fail
    tab->row:get normal row with preb data
    tab->tab:update table
    tab-->user:updated table
    tab-->user:error message
end



@enduml