@startuml login
actor user
participant server as serv
database dataManager as dm
participant navigator as nav

user->serv:login
serv->dm:check user
dm-->serv:user data
serv->serv:generate token
serv->dm:store token
serv-->user:token
user->serv:navigate home(token)
serv->nav:get home address(token)
nav-->serv:home address
serv-->user:home address
@enduml