@startuml new user
actor manager as man
participant server as serv
database dataManager as db
man->serv:add user(token,userData)
serv->serv:check token
serv->db:add user
alt can create user
    db->db:create user[user not exists]
    db-->serv:user token
    serv-->man:user token
else the user already exists
    db-->serv:user already exists
    serv-->man:user already exists
end
@enduml