@startuml upload safe
actor user
participant server as serv
database dataManager as db

user->serv:upload safe(safe,key)
serv->serv:checkSafe(safe,key)
alt safe ok
    serv->db:get last safe number of user(user)
    db-->serv:last number
    serv->db:store safe(safe text,safe bytecode,key text,key bytecode,user,safe number)
    db->db:store
    alt success
        db-->serv:ok
        serv-->user:ok
    else fail
        db-->serv:error
        serv-->user:error
    end
else
    serv-->user:safe error(checkSafe results)
end
